# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: QLC+ (QLC Plus) add-on
version: "4.12.6"
slug: qlcplus
description: An Add-on to run the light controller (DMX) Software QLC+.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-qlcplus"
